# Generated by Django 6.0.4 on 2026-08-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        # Update field choices and defaults on the Client model
        migrations.AlterField(
            model_name='client',
            name='currency_code',
            field=models.CharField(
                choices=[
                    ('KES', 'Kenyan Shilling (KSh)'),
                    ('USD', 'US Dollar ($)'),
                    ('EUR', 'Euro (\u20ac)'),
                    ('GBP', 'British Pound (\u00a3)'),
                    ('UGX', 'Ugandan Shilling (USh)'),
                    ('TZS', 'Tanzanian Shilling (TSh)'),
                    ('NGN', 'Nigerian Naira (\u20a6)'),
                    ('INR', 'Indian Rupee (\u20b9)'),
                    ('CAD', 'Canadian Dollar (C$)'),
                    ('AUD', 'Australian Dollar (A$)'),
                    ('ZAR', 'South African Rand (R)'),
                    ('GHS', 'Ghanaian Cedi (\u20b5)'),
                ],
                default='KES',
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name='client',
            name='currency_symbol',
            field=models.CharField(default='KSh', max_length=5),
        ),
        migrations.AlterField(
            model_name='client',
            name='timezone',
            field=models.CharField(default='Africa/Nairobi', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(default='Kenya', max_length=100),
        ),
        # Update existing tenants from USD to KSh (only those still using defaults)
        migrations.RunSQL(
            sql="UPDATE tenants_client SET currency_code='KES', currency_symbol='KSh' WHERE currency_code='USD' AND currency_symbol='$';",
            reverse_sql="UPDATE tenants_client SET currency_code='USD', currency_symbol='$' WHERE currency_code='KES' AND currency_symbol='KSh';",
        ),
    ]
