# Generated by Django 6.0.4 on 2026-08-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_currency_defaults_ksh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(default='United States', max_length=100),
        ),
    ]
