# Generated by Django 6.0.4 on 2026-08-12 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('sales_summary', 'Sales Summary'), ('sales_by_product', 'Sales by Product'), ('sales_by_branch', 'Sales by Branch'), ('sales_by_cashier', 'Sales by Cashier'), ('inventory_valuation', 'Inventory Valuation'), ('low_stock', 'Low Stock Report'), ('profit_margin', 'Profit Margin'), ('tax_collected', 'Tax Collected'), ('top_customers', 'Top Customers'), ('daily_revenue', 'Daily Revenue'), ('payment_methods', 'Payment Methods Breakdown'), ('stock_movement', 'Stock Movement Report')], max_length=30)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
