# Generated by Django 6.0.8 on 2026-08-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Optional expiry date for perishable goods.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='items_per_unit',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Number of individual pieces per unit (e.g., 24 for a carton, 12 for a dozen).'),
        ),
    ]
