# Generated by Django 6.0.4 on 2026-08-12 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sale'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='taxpayment',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.tax'),
        ),
    ]
