# Generated by Django 6.0.4 on 2026-08-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_customerinvoice_customerinvoiceline_invoicepayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='expense',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
