# Generated by Django 6.0.4 on 2026-08-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='poscredit',
            index=models.Index(fields=['due_date'], name='pos_poscred_due_dat_b2cd43_idx'),
        ),
        migrations.AddConstraint(
            model_name='poscredit',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='pos_credit_balance_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='poscredit',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__lte', models.F('total_amount'))), name='pos_credit_paid_not_exceed_total'),
        ),
    ]
