# Generated by Django 6.0.8 on 2026-08-21 01:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcoupon',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.AlterField(
            model_name='billingrate',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.AlterField(
            model_name='billingrate',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0770'), help_text='Cost per `requests_per_unit` block.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlybill',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
    ]
