# Generated by Django 6.0.4 on 2026-08-14 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0002_initial'),
        ('products', '0004_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_number', models.CharField(max_length=50, unique=True)),
                ('adjustment_type', models.CharField(choices=[('increase', 'Quantity Increase'), ('decrease', 'Quantity Decrease'), ('set', 'Set Exact Quantity')], max_length=10)),
                ('reason', models.CharField(choices=[('cycle_count', 'Cycle Count Correction'), ('damage', 'Damage / Spoilage'), ('theft', 'Theft / Shrinkage'), ('expiry', 'Expired / Obsolete'), ('sample', 'Sample / Demo / Promotion'), ('gift', 'Gift / Donation'), ('conversion', 'Unit Conversion'), ('clerical', 'Clerical / Data Entry Error'), ('quality', 'Quality / Recall'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('adjustment_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('total_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('total_value_impact', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('counted_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('quantity_change', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('value_impact', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockadjustment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['branch', 'status'], name='inventory_s_branch__5d7bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['reason'], name='inventory_s_reason_e3ab92_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['adjustment_date'], name='inventory_s_adjustm_ec33d6_idx'),
        ),
    ]
