# Generated by Django 6.0.4 on 2026-08-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockadjustment_stockadjustmentline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(choices=[('cycle_count', 'Cycle Count Correction'), ('damage', 'Damage / Spoilage'), ('theft', 'Theft / Shrinkage'), ('expiry', 'Expired / Obsolete'), ('sample', 'Sample / Demo / Promotion'), ('gift', 'Gift / Donation'), ('conversion', 'Unit Conversion'), ('clerical', 'Clerical / Data Entry Error'), ('quality', 'Quality / Recall'), ('po_received', 'PO Received'), ('other', 'Other')], max_length=20),
        ),
    ]
