# Generated by Django 6.0.4 on 2026-08-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0004_add_po_received_reason'),
        ('products', '0005_add_expiry_date_and_items_per_unit'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', 0)), name='stock_quantity_on_hand_nonneg'),
        ),
    ]
