# Generated by Django 6.0.4 on 2026-09-02 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0005_stockitem_stock_quantity_on_hand_nonneg'),
        ('products', '0006_product_products_pr_is_acti_ca4d9a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockcountline',
            options={'ordering': ['product__sku']},
        ),
        migrations.AddField(
            model_name='stockcount',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stock_counts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='count_type',
            field=models.CharField(choices=[('full', 'Full Count'), ('partial', 'Partial Count'), ('cycle', 'Cycle Count'), ('abc', 'ABC Class Count')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='counted_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_stock_counts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='title',
            field=models.CharField(blank=True, help_text='Human-friendly name for this count session.', max_length=200),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='total_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='total_variance_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='total_variance_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='counted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='counted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counted_stock_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='line_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('counted', 'Counted'), ('flagged', 'Flagged for Recount'), ('not_found', 'Not Found')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='value_variance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reviewed', 'Reviewed'), ('reconciled', 'Reconciled'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='stockcountline',
            unique_together={('stock_count', 'product', 'variant')},
        ),
        migrations.AddIndex(
            model_name='stockcount',
            index=models.Index(fields=['branch', 'status'], name='inventory_s_branch__54d769_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcount',
            index=models.Index(fields=['count_type'], name='inventory_s_count_t_b504fd_idx'),
        ),
    ]
