# Generated by Django 6.0.8 on 2026-08-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('user_role', models.CharField(default='', max_length=30)),
                ('user_name', models.CharField(blank=True, default='', max_length=255)),
                ('branch', models.CharField(blank=True, default='', max_length=100)),
                ('jti', models.CharField(db_index=True, help_text='JWT ID claim', max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('login_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='JWT access token expiry')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['is_active', 'expires_at'], name='security_ac_is_acti_307adf_idx'), models.Index(fields=['user_id', 'is_active'], name='security_ac_user_id_bab270_idx')],
            },
        ),
    ]
