# Generated by Django 6.0.4 on 2026-08-12 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gateway_refund_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50, unique=True)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('wallet', 'Mobile Wallet'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('store_credit', 'Store Credit'), ('gift_card', 'Gift Card'), ('crypto', 'Crypto'), ('on_account', 'On Account (Credit)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='captured', max_length=20)),
                ('gateway', models.CharField(blank=True, help_text='e.g., Stripe, Square, Flutterwave', max_length=50)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=200)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_brand', models.CharField(blank=True, max_length=30)),
                ('auth_code', models.CharField(blank=True, max_length=50)),
                ('tendered', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('change_given', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='branches.branch')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
